version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: maria-db-phpmyadmin_app_1
      APP_PORT: 80
    
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "4agNTgoV5GGJw-zily_5pC"
      TZ: Europe/Berlin
    ports:
      - 3307:3306
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql

  app:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db